version = "3.8.1" // Latest Scalafmt version compatible with sbt-scalafmt 2.5.0
runner.dialect = scala3
align.preset = more
maxColumn = 120
rewrite.rules = [SortImports, RedundantBraces]
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = false // Or true, if you prefer
rewrite.scala3.insertEndMarkerMinLines = 15 // Add end markers for blocks longer than 15 lines
